[project]
name = "map-agent-chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.7"
dependencies = [
    "folium>=0.20.0",
    "geopy>=2.4.1",
    "pydantic-ai>=1.21.0",
    "streamlit>=1.51.0",
    "streamlit-folium>=0.25.3",
]
